# Generated by Django 4.2.4 on 2023-11-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default-movie.png', upload_to='movie_pics'),
        ),
    ]
