# Generated by Django 4.2.4 on 2023-11-22 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate_value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
